# Conclusion

The first part is to investigate whether vaccination has an impact on the spread of COVID-19. By analyzing the five states with the largest number of vaccinations, we found that the vaccination rate is inversely related to the spread of the epidemic. This relationship has also been confirmed by national data. From this we can get that vaccination can curb the spread of the epidemic.

The second part is to analyze the relationship between hospital-related data and mortality. According to analysis, we did not find a clear relationship between hospital capacity and mortality. This may be due to other factors affecting the relationship between these two. So, in order to further analyze, we will collect more hospital-related data, similar to data such as number of ventilators or the number of doctors. Under the control of other variables, we will do further analysis. Regarding the relationship between hospitalization rate and death rate, we found that hospitalization rate and death rate are positively correlated. One possible explanation is that people may only be hospitalized for treatment when they become severely ill. And because there is no specific medicine, it is difficult for severely ill patients to be cured, which leads to a positive correlation. 

The last part....